name: CI

on:
  push:
    branches:
      - master

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build extension repo
    needs: check_wrapper
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy CI gradle.properties 
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Make gradle and sign-apk.sh executeable
        run: |
          chmod +x ./gradlew
          chmod +x ./.github/scripts/sign-apks.sh
          chmod +x ./.github/scripts/create-repo.sh
          chmod +x ./.github/scripts/commit-repo.sh

      - name: Build extensions
        uses: gradle/gradle-build-action@v2
        env:
          CI_PUSH: "true"
        with:
          arguments: assembleRelease
      
      - name: Sign APKs
        run: |
          ./.github/scripts/sign-apks.sh \
            ${{ secrets.SIGNING_KEY }} \
            ${{ secrets.ALIAS }} \
            ${{ secrets.KEY_STORE_PASSWORD }} \
            ${{ secrets.KEY_PASSWORD }}

      - name: Checkout repo branch
        uses: actions/checkout@v2
        with:
          ref: repo
          path: repo

      - name: copy apks
        run: |
          cp -f ./apk/* ./repo/
          cd repo
          ls
      - name: Deploy repo
        run: |
          cd repo
          ../.github/scripts/commit-repo.sh